name: link-check
on:
pull_request:
schedule:
  - cron: "0 8 * * 1" # Mondays 08:00 UTC
jobs:
lychee:
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v4
  - name: Check links with lychee
uses: lycheeverse/lychee-action@v1
with:
args: --no-progress --verbose --exclude-mail --timeout 20 .
